### ISSUE TITLE
Re factorización de las interfaces e implementación de los diseños del diseñador grafico  

### ISSUE THREAD

**Issue by CriistiianDM** [CriistiianDM/dui-iglesias-software-samuel#101]
Hacer los respetivos cambios a todas las interfaces para que se vean mas bonitas y de forma mas profesional e implementación del home por el diseñador grafico, tratare de hacerlo rápido por que después me enfoco en meter la funcionalidad de ver los grupos y poder añadir personas - ya con eso seria lo básico para moverse en la aplicación, si da el tiempo podemos meter la configuración de la tabla de usuarios - interfaces de los demás cargos - asistencia - ver la info de la iglesia - cumpleaños - en la sesión de profile hacer las funcionalidades faltantes

**Comment by CriistiianDM** [comment]
![image](https://user-images.githubusercontent.com/62184928/184067610-28f89318-4c38-4f6f-9f3b-323228ed3246.png)
nuevo home, solo falta responsearlo y pasar con las demás interfaces

**Comment by CriistiianDM** [comment]
![image](https://user-images.githubusercontent.com/62184928/184231839-7fa1089f-eb92-45a2-8803-fcc2dca5ab55.png)
version final del home :kissing_heart: :smiling_face_with_three_hearts:

**Comment by JuanSe320** [comment]
![image](https://user-images.githubusercontent.com/63017408/184268774-009df985-cf18-4d88-9bcb-c209c258dd0d.png)
nueva interfaz de cargos mas acorde a el nuevo home

**Comment by CriistiianDM** [comment]
Me duele el alma de pensar que el cliente prefiere mas funcionalidades antes que todas las interfaces sean obras de arte. :broken_heart: :anger: :zzz:

**Comment by CriistiianDM** [comment]
![image](https://user-images.githubusercontent.com/62184928/184436697-26cb8501-9689-4695-9c88-d06fa17fa9f7.png)
creacion de la nueva vista para la funcionalidad de los grupos

**Comment by CriistiianDM** [comment]
![image](https://user-images.githubusercontent.com/62184928/184453200-b45557c1-1949-49d4-9dbc-fc143f842e57.png)
ya quedo con la logica, mientras se hace la consulta en internets lentos, mostrala que no tienes grupos

**Comment by CriistiianDM** [comment]
![image](https://user-images.githubusercontent.com/62184928/184510681-d6253ddf-a27a-404f-b55d-c52ed157728a.png)
ya quedo toda la logica lista

**Comment by CriistiianDM** [comment]
Este issue y las interfaces que mande el diseñador grafico, las continua al que contraten para terminar el proyecto
