### ISSUE TITLE
Cuidades de cada region de colombia  en base de datos

### ISSUE THREAD

**Issue by CriistiianDM** [CriistiianDM/dui-iglesias-software-samuel#20]
Hay que rellenar en la tabla city todas las cuidades de cada region de colombia
![image](https://user-images.githubusercontent.com/62184928/177018925-bf873aa9-42dd-47be-aff5-2c95c703c4c0.png)
hay en la carpeta bd/  dentro del archivo colocar los comandos de inserción siguiendo la sintaxis

Tratare de desplegar la bd a un servidor gratis de heroku pa que los cambios finales como esas tablas solo hagamos en la principal y no tengas que ir exportando tablas y pasándolas a nuestra local

**Comment by CriistiianDM** [comment]
mas rato termino la logica del login y ya dejo los issue pa que avancemos en el desarrollo de la logica

**Comment by CriistiianDM** [comment]
se que coloque 81 paises pero solo sera en colombia la region, ya luego si hay usuarios de otros paises veremos como afrontaremos ese problema

**Comment by CriistiianDM** [comment]
@JuanSe320  con todas las inserciones que has hecho a la base de datos, estoy muy contento. considero que puedes dejar hasta ahi

**Comment by JuanSe320** [comment]
listo entonces lo cerrare
