### ISSUE TITLE
Testear los middleware 

### ISSUE THREAD

**Issue by CriistiianDM** [CriistiianDM/dui-iglesias-software-samuel#95]
He creado 2 middleware, solo testea el de la creación de grupo y trata de encontrar errores en el fronted, igual si logras mandar algo mal, en el backend se verifica lo que le llega antes de mandarlo al control, pasare a blindar la parte de los cargos y ya con eso seguire en la seguridad del backend.

**Comment by JuanSe320** [comment]
Cree un usuario y un grupo y se crearon correctamente los middleware estan funcionando
